/*******************************************************************************
 Test Name:         dsql_domain_21
 Test Series:       dsql_domains
 Date:              20-Oct-1993
 Related bugs:      bug_xxxx  -  have to exit db for changes made to domains 
                                 to affect data being entered into tables.
 Comments:          This script will test using the alter domain statement on
                    domains that are already in use in table definitions, with
                    domain defaults and check constraints.
/*******************************************************************************
HISTORY:
1998-Dec-16 David Schnepper & Stas Tsikin
Bulk edit of WHERE_EXAMPLES TO WHERE_EXAMPLES_40 performed
Bulk edit of $RUN drop_gdb TO $DROP performed

$ GBAK -r WHERE_EXAMPLES_40:atlas.gbak WHERE_GDB:atlas.gdb
$ isql WHERE_GDB:atlas.gdb
create domain dom20a as smallint 
 default 0
 check (value >= 0 and value < 100);
commit;
show domain dom20a;
create domain dom20b as integer
 default 500
 check (value >= 500);
commit;
show domain dom20b;
create domain dom20c as date
 check (value >= 'today');
commit;
show domain dom20c;
create domain dom20d as char(20)
 check (value in (select river from rivers));
commit;
show domain dom20d;
create domain dom20e as varchar(25)
 default 'VARYING DEFAULT';
commit;
show domain dom20e;
create domain dom20f as decimal(6,2)
 default 4.2
 check (value > 0);
commit;
show domain dom20f;
create domain dom20g as float
 default 500.1
 check (value < 50000.00);
commit;
show domain dom20g;
create domain dom20h as double precision
 default 1000
 check (value > 99.999);
commit;
show domain dom20h;
create table tab20a
 (fld1 dom20a, fld2 dom20b, fld3 dom20c, fld4 dom20d,
  fld5 dom20e, fld6 dom20f, fld7 dom20g, fld8 dom20h);
commit;
show table tab20a;
/* This should give a violation for fld4 since Sacramento is not among the rivers
*/
insert into tab20a (fld3, fld4) values ('01/01/2050', 'Sacramento');
commit;
alter domain dom20a
 drop default;
alter domain dom20a
 drop constraint;
commit;
alter domain dom20a
 add constraint check (value > 100);
commit;
show domain dom20a;
commit;
exit;
$ isql WHERE_GDB:atlas.gdb
show domain dom20a;
insert into tab20a (fld1, fld3, fld4) values (250, '01/01/2050', 'Sacramento');
commit;
select * from tab20a;
rollback;
exit;
$ DROP WHERE_GDB:atlas.gdb
