$CREATE COMMENT
*******************************************************************************
 
Test Name:  	EXT_REL_0_3_D
Test Level:     0
Series Name:    EXT_LEV_0
Date:  		June 28, 1994
Author:  	Scott Van Voris
Bug: 
 
Description:    This is a Level 0 test which is designed to verify the 
		syntax to create an external relation with a fixed-length
		datatype is working properly.

                In order to verify the external relation was really 
                created, a tuple is inserted into the relation, and the 
                value in the relation retreived via a query.
 
Expected Output:        Use CONNECT or CREATE DATABASE to specify a database
			Use CONNECT or CREATE DATABASE to specify a database
			Database:  ext_rel.gdb
 
			FIELD1 
			====== 
 
			 12000 
 
History:

2-Oct-95:  Mark
  Removed the Cleanup / Setup comments from the test.
  Also, added WHERE_GDB and RUN drop_gdb to the tests.

3-Oct-95: Marco
  Added the WHERE_GDB_EXTERNAL, so the external file can be created 
  by the server in the correct place when accessing data remotely.
  Also, I removed any referance to DIR external.dat and TYPE external.dat
  which would also fail when running remotely.

27-8-97: dsmirnov: replaced RUN drop_gdb to $DROP
         The test does not delete remote external.dat since $DELETE does not
         work remotely.
         So may a previous one. This may cause problems when performing select
         because we may operate with external.dat file left undeleted from
         the previous testcase.

7-Oct-99: Linda Begley
  Added rm_file.sh so that external file external.dat can be remotely removed. 

14-Oct-00: Frank Schlottmann-Goedde
  replaced double with single quotes where necessary to run with version 6.x
*******************************************************************************

$CREATE isql.in

CREATE DATABASE 'WHERE_GDB:ext_rel.gdb';

CREATE TABLE ext_table EXTERNAL FILE 'WHERE_GDB_EXTERNAL:external.dat'
       (field1 SMALLINT) ;

$CREATE isql2.in

CONNECT 'WHERE_GDB:ext_rel.gdb';
INSERT INTO ext_table (field1) VALUES (12000);
SELECT * FROM ext_table;

$CREATE rm_file.sh
machine=`uname -s`
node=`uname -n`
echo $WHERE_GDB_EXTERNAL > awk.tst

echo $WHERE_GDB > ls.out
proto=`cut -c 1,2 ls.out`

if [ $machine = "Windows_NT" ] || [ $machine = "Windows_95" ] || [ $machine = "Windows_98" ]
   then 
      if [ $WHERE_GDB = $WHERE_GDB_EXTERNAL ]
        then  
           rm -f WHERE_GDB_EXTERNAL:external.dat 
        else
           if [ $proto = "//" ]
              then
              machine_name=`awk -F"/" '{print $3}' ls.out`
              else
              machine_name=`awk -F":" '{print $1}' ls.out` 
           fi
           echo `awk -F":" '{print $1}' awk.tst` > awk.out
           server_testbed=`cat awk.out`
           ls_string=//$machine_name/$server_testbed/testbed/external.dat
           rm -f $ls_string 
      fi
else
      if [ $WHERE_GDB = $WHERE_GDB_EXTERNAL ]
        then  
           rm -f WHERE_GDB_EXTERNAL:external.dat 
        else
           if [ $proto = "//" ]
              then
              machine_name=`awk -F"/" '{print $3}' ls.out`
              else
              machine_name=`awk -F":" '{print $1}' ls.out` 
           fi
           rsh $machine_name /bin/rm -f WHERE_GDB_EXTERNAL:external.dat
      fi
fi

$ISQL -input isql.in
$ISQL -input isql2.in
$DROP WHERE_GDB:ext_rel.gdb
$SH rm_file.sh
$DELETE COMMENT isql.in isql2.in rm_file.sh
