HISTORY:
1998-Dec-16 David Schnepper & Stas Tsikin
Bulk edit of WHERE_EXAMPLES TO WHERE_EXAMPLES_40 performed
Bulk edit of $RUN drop_gdb TO $DROP performed

$ GBAK -r WHERE_EXAMPLES_40:atlas.gbak WHERE_GDB:atlas.gdb
$ COPY WHERE_FILES:sh_test.h sh_test.h
$ CREATE join001.e

/*
 Out join example 2.9.1 page 64
 
*/


DATABASE atlas = FILENAME "WHERE_GDB:atlas.gdb";
#include <stdio.h>
#include "sh_test.h"

BASED_ON CITIES.CITY		City;
BASED_ON STATES.STATE_NAME	State_Name;

short StateFlag;


EXEC SQL
	INCLUDE SQLCA;


main()
{

EXEC SQL
	DECLARE C CURSOR FOR
	SELECT C.CITY, S.STATE_NAME  
	FROM CITIES C LEFT JOIN STATES S ON S.STATE = C.STATE;
	
EXEC SQL
	OPEN C;


printf("City \t\t\t State\n");
printf("---- \t\t\t ------\n");

do{
	EXEC SQL FETCH C INTO :City, :State_Name:StateFlag;
	if (!SQLCODE){
		if (StateFlag)
			strcpy(State_Name,"- NULL -");
		printf ("%-20s ",City);
		printf (" %-20s\n", State_Name);
	}
}while (SQLCODE == 0);

EXEC SQL CLOSE C;

printf("... End of example 2.9.1 \n");
}
$ GPRE -e join001.e
$ CC FLAG_CC join001
$ LINK FLAG_LINK join001 LIBRARIES
$ RUN join001
$ CREATE join001.qli
ready WHERE_GDB:atlas.gdb;
set semicolon;
set columns 100;
SELECT CITY, STATE FROM CITIES C LEFT JOIN STATES S ON S.STATE = C.STATE;
finish;
quit;
$ QLI -n -a join001.qli
$ CREATE join001.sql
connect WHERE_GDB:atlas.gdb;
SELECT CITY, STATE FROM CITIES C LEFT JOIN STATES S ON S.STATE = C.STATE;
quit;
$ISQL -i join001.sql
$DROP WHERE_GDB:atlas.gdb
$ DELETE join001* join001.sql sh_test.h
