$ GBAK -r WHERE_FILES:sh_join.gbk WHERE_GDB:sh_join.gdb
$ COPY WHERE_FILES:sh_test.h sh_test.h
$ CREATE join015.e

/**********************************************************************
 Purpose:               Test SQL OUTER JOIN support in InterBase 4.0
 Description:           GROUP BY clause on joined table
 Author:                Sam Hakim, June 1, 93
 ***********************************************************************
*/

#include <stdio.h>
#include "sh_test.h"

DATABASE DB = "WHERE_GDB:sh_join.gdb";
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON st5.s1      t1s1;
BASED_ON st5.s1      sums1;

char Test[]="\
select sum(x.s1), x.s1 \
from (st5 x left join st2 y on x.s1 = y.s1) \
group by x.s1";

void Underline();

main()
{
	
    int Count;
	Count = 0;
    printf ("Test:\n %s\n",Test);
    Underline(80);

    EXEC SQL
                DECLARE CR CURSOR FOR
                select sum(x.s1), x.s1
                from (st5 x left join st2 y on x.s1 = y.s1)
                group by x.s1; 

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :sums1,:t1s1;


        while (SQLCODE == 0){
		Count++;

                printf("%d     ",sums1);
                printf("%d\n",t1s1);
		
                EXEC SQL
                FETCH CR INTO :sums1,:t1s1;

        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        gds_$print_status(gds_$status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e join015.e
$ CC FLAG_CC join015
$ LINK FLAG_LINK join015 LIBRARIES
$ RUN join015
$ CREATE join015.qli
ready WHERE_GDB:sh_join.gdb;
set semicolon;
set columns 100;
select sum(x.s1), x.s1
from (st5 x left join st2 y on x.s1 = y.s1) 
group by x.s1;
finish;
quit;
$ QLI -n -a join015.qli
$ CREATE join015.sql
connect WHERE_GDB:sh_join.gdb;
select sum(x.s1), x.s1
from (st5 x left join st2 y on x.s1 = y.s1) 
group by x.s1;
quit;
$ISQL -i join015.sql
$RUN drop_gdb WHERE_GDB:sh_join.gdb
$ DELETE join015*  sh_test.h

