$ GBAK -r WHERE_FILES:sh_join.gbk WHERE_GDB:sh_join.gdb
$ COPY WHERE_FILES:sh_test.h sh_test.h
$ CREATE join028.e

/**********************************************************************
 Purpose:               Test SQL OUTER JOIN support in InterBase 4.0
 Description:           Count(*) of an outer join query
 Author:                Sam Hakim, June 1, 93
 ***********************************************************************
*/

#include <stdio.h>
#include "sh_test.h"

DATABASE DB = "WHERE_GDB:sh_join.gdb";
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

unsigned short      RecCount;

char Test[]="\
select count(*) \
from (st5 x full join st1 y on x.s2 = y.s2)";

void Underline();

main()
{
	
    int Count;
	Count = 0;
    printf ("Test:\n %s\n",Test);
    Underline(80);

    EXEC SQL
                DECLARE CR CURSOR FOR
                select count(*)
                from (st5 x full join st1 y on x.s2 = y.s2);

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :RecCount;

        while (SQLCODE == 0){
		Count++;

                printf("%d  ",RecCount);

                EXEC SQL
                FETCH CR INTO :RecCount;
        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;

exit(0);

ERR:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        gds_$print_status(gds_$status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e join028.e
$ CC FLAG_CC join028
$ LINK FLAG_LINK join028 LIBRARIES
$ RUN join028
$ CREATE join028.qli
ready WHERE_GDB:sh_join.gdb;
set semicolon;
set columns 100;

/* qli core dumps */
select count(*)
from (st5 x full join st1 y on x.s2 = y.s2);

finish;
quit;
$ QLI -n -a join028.qli
$ CREATE join028.sql
connect WHERE_GDB:sh_join.gdb;
select count(*)
from (st5 x full join st1 y on x.s2 = y.s2);
quit;
$ISQL -i join028.sql
$RUN drop_gdb WHERE_GDB:sh_join.gdb
$ DELETE join028*  sh_test.h
