HISTORY:
1998-Dec-16 David Schnepper & Stas Tsikin
Bulk edit of WHERE_EXAMPLES TO WHERE_EXAMPLES_40 performed
Bulk edit of $RUN drop_gdb TO $DROP performed

$ GBAK -r WHERE_EXAMPLES_40:atlas.gbak WHERE_GDB:atlas.gdb
$ COPY WHERE_FILES:sh_test.h sh_test.h
$ CREATE join003.e

/*
 Out join example 2.9.1 page 64 - 3
 
*/


DATABASE atlas = FILENAME "WHERE_GDB:atlas.gdb";
#include <stdio.h>
#include "sh_test.h"

BASED_ON BASEBALL_TEAMS.TEAM_NAME	Team_Name;
BASED_ON CITIES.CITY			City;
BASED_ON STATES.STATE_NAME		State_Name;

short StateFlag;


EXEC SQL
	INCLUDE SQLCA;

main()
{

EXEC SQL
	DECLARE C CURSOR FOR
	SELECT B.TEAM_NAME, C.CITY, S.STATE_NAME  
	FROM (CITIES C LEFT JOIN STATES S ON S.STATE = C.STATE)
	INNER JOIN BASEBALL_TEAMS B ON B.CITY = C.CITY
	ORDER BY B.TEAM_NAME;
	
EXEC SQL
	OPEN C;


printf("Team Name \t\t City \t\t State\n");
printf("--------- \t\t ---- \t\t ------\n");

do{
	EXEC SQL FETCH C INTO :Team_Name,:City, :State_Name:StateFlag;
	if (!SQLCODE){
		if (StateFlag)
			strcpy(State_Name,"- NULL -");
		printf ("%-20s ",Team_Name);
		printf ("%-20s ",City);
		printf (" %-20s\n", State_Name);
	}
}while (SQLCODE == 0);

EXEC SQL CLOSE C;

printf("... End of example 2.9.1 \n");
}
$ GPRE -e join003.e
$ CC FLAG_CC join003
$ LINK FLAG_LINK join003 LIBRARIES
$ RUN join003
$ CREATE join003.qli
ready WHERE_GDB:atlas.gdb;
set semicolon;
set columns 100;
SELECT B.TEAM_NAME, C.CITY, S.STATE_NAME
FROM (CITIES C LEFT JOIN STATES S ON S.STATE = C.STATE)
INNER JOIN BASEBALL_TEAMS B ON B.CITY = C.CITY ORDER BY B.TEAM_NAME;
finish;
quit;
$ QLI -n -a join003.qli
$ CREATE join003.sql
connect WHERE_GDB:atlas.gdb;
SELECT B.TEAM_NAME, C.CITY, S.STATE_NAME
FROM (CITIES C LEFT JOIN STATES S ON S.STATE = C.STATE)
INNER JOIN BASEBALL_TEAMS B ON B.CITY = C.CITY ORDER BY B.TEAM_NAME;
quit;
$ISQL -i join003.sql
$DROP WHERE_GDB:atlas.gdb
$ DELETE join003*  sh_test.h join003.sql
