HISTORY:
1998-Dec-16 David Schnepper & Stas Tsikin
Bulk edit of WHERE_EXAMPLES TO WHERE_EXAMPLES_40 performed
Bulk edit of $RUN drop_gdb TO $DROP performed

$ GBAK -r WHERE_EXAMPLES_40:atlas.gbak WHERE_GDB:atlas.gdb
$ COPY WHERE_FILES:sh_test.h sh_test.h
$ CREATE join002.e

/*
 Out join example 2.9.1 page 64 - 2
 
*/


DATABASE atlas = FILENAME "WHERE_GDB:atlas.gdb";
#include <stdio.h>
#include "sh_test.h"

BASED_ON CITIES.CITY		City;
BASED_ON STATES.STATE_NAME	State_Name;

short StateFlag;


EXEC SQL
	INCLUDE SQLCA;


main()
{

EXEC SQL
	DECLARE C CURSOR FOR
	SELECT C.CITY, S.STATE_NAME  
	FROM CITIES C LEFT JOIN STATES S ON S.STATE = C.STATE
	WHERE C.CITY STARTING WITH 'San';
	
EXEC SQL
	OPEN C;


printf("City \t\t\t State\n");
printf("---- \t\t\t ------\n");

do{
	EXEC SQL FETCH C INTO :City, :State_Name:StateFlag;
	if (!SQLCODE){
		if (StateFlag)
			strcpy(State_Name,"- NULL -");
		printf ("%-20s ",City);
		printf (" %-20s\n", State_Name);
	}
}while (SQLCODE == 0);

EXEC SQL CLOSE C;

printf("... End of example 2.9.1 \n");
}
$ GPRE -e join002.e
$ CC FLAG_CC join002
$ LINK FLAG_LINK join002 LIBRARIES
$ RUN join002
$ CREATE join002.qli

ready WHERE_GDB:atlas.gdb;
set semicolon;
SELECT C.CITY, S.STATE_NAME
FROM CITIES C LEFT JOIN STATES S ON S.STATE = C.STATE
WHERE C.CITY STARTING WITH 'San';
finish;
quit;
$ QLI -n -a join002.qli
$ CREATE join002.sql
connect WHERE_GDB:atlas.gdb;
SELECT C.CITY, S.STATE_NAME
FROM CITIES C LEFT JOIN STATES S ON S.STATE = C.STATE
WHERE C.CITY STARTING WITH 'San';
quit;
$ISQL -i join002.sql
$DROP WHERE_GDB:atlas.gdb
$ DELETE join002*  sh_test.h join002.sql
