#!/bin/sh
# The contents of this file are subject to the InterBase Public License
# Version 1.0 (the "License"); you may not use this file except in
# compliance with the License.
#
# You may obtain a copy of the License at http://www.Inprise.com/IPL.html.
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.  The Original Code was created by Inprise
# Corporation and its predecessors.
#
# Portions created by Inprise Corporation are Copyright (C) Inprise
# Corporation. All Rights Reserved.
#
# Contributor(s): ______________________________________.

TEST_DIR=`pwd`

date

# try to clean up after the last test run
# do this after killing processes just in case they are still
# trying to write.
rm -f core
rm -f *.gdb *.gbk
rm -f *.e *.o *.c *.h
rm -f *.lib *.sql *.gdl
rm -f tcs.*
rm -f *.tmp


INTERBASE=/opt/interbase
export INTERBASE

PATH=$INTERBASE/bin:$PATH
export PATH
LD_LIBRARY_PATH=/usr/lib
export LD_LIBRARY_PATH
SHLIB_PATH=/usr/lib
export SHLIB_PATH
LD_RUN_PATH=/usr/lib:$TEST_DIR
export LD_RUN_PATH

ISC_USER=sysdba
ISC_PASSWORD=masterkey
export ISC_USER
export ISC_PASSWORD
$INTERBASE/bin/gsec -delete qa_user1
$INTERBASE/bin/gsec -delete qa_user2
$INTERBASE/bin/gsec -delete qa_user3
$INTERBASE/bin/gsec -delete qa_user4
$INTERBASE/bin/gsec -delete qa_user5
$INTERBASE/bin/gsec -add qa_user1 -pw qa_user1
$INTERBASE/bin/gsec -add qa_user2 -pw qa_user2
$INTERBASE/bin/gsec -add qa_user3 -pw qa_user3
$INTERBASE/bin/gsec -add qa_user4 -pw qa_user4
$INTERBASE/bin/gsec -add qa_user5 -pw qa_user5
# test v4_api15
$INTERBASE/bin/gsec -delete guest
$INTERBASE/bin/gsec -add guest    -pw guest
# series gf_shutdown &  gf_shut_l1
$INTERBASE/bin/gsec -delete shut1
$INTERBASE/bin/gsec -add shut1    -pw shut1
# series gf_shut_l1
$INTERBASE/bin/gsec -delete shut2
$INTERBASE/bin/gsec -add shut2    -pw shut2
# series nist3
# series procs_qa_bugs, test bug_6015
$INTERBASE/bin/gsec -delete qatest
$INTERBASE/bin/gsec -add qatest             -pw qatest

if [ $? != 0 ]; then
    echo "ERROR: Failure adding users"
    exit 1		# failure adding users
fi

unset ISC_USER
unset ISC_PASSWORD
export ISC_USER
export ISC_PASSWORD

#
# environment settings for test run
#

# "setting up local environment"
    RUN_TYPE=local
    RUN_TAG=TEST
    KNOWN_FAILURES_TAG=$PLATFORM.known_failures
    WHERE_GDB=$TEST_DIR
    WHERE_GDB1=$TEST_DIR
    WHERE_GDB2=$TEST_DIR
    WHERE_GDB3=$TEST_DIR
    REMOTE_DIR=$TEST_DIR
    REMOTE_DIR1=$TEST_DIR
    REMOTE_DIR11=$TEST_DIR
    WHERE_GSEC_REMOTE=/opt/interbase
    WHERE_GSEC=/opt/interbase
    WHERE_REMOTE=$TEST_DIR
    UDF_LIBPATH=$TEST_DIR
    WHERE_UDF=/opt/interbase/UDF
    WHERE_GDB_EXTERNAL=$TEST_DIR
    SERVICE_MGR=service_mgr
    unset ISC_PATH

export WHERE_GDB
export WHERE_GDB1
export WHERE_GDB2
export WHERE_GDB3
export REMOTE_DIR
export REMOTE_DIR1
export REMOTE_DIR11
export WHERE_GSEC_REMOTE
export WHERE_GSEC
export WHERE_REMOTE
export UDF_LIBPATH
export WHERE_UDF
export WHERE_GDB_EXTERNAL
export SERVICE_MGR

tcs
